/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125505-gc57660fb18-20260708"
#endif /* AVUTIL_FFVERSION_H */
