/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124852-g025d6330a5-20260606"
#endif /* AVUTIL_FFVERSION_H */
